In [2]:
import cv2                  
import numpy as np          
import os                   
from random import shuffle  
from tqdm import tqdm      
TRAIN_DIR = 'C:\\Users\\hp\\Desktop\\web login\\New folder\\dataset'

IMG_SIZE = 50
LR = 1e-3

MODEL_NAME = 'dogsvscats-{}-{}.model'.format(LR, '2conv-basic') 

In [3]:
def label_img(img):
    word_label = img[:6]
    if word_label == 'cattle': return [1,0]
    else:
        return [0,1]

In [4]:
def create_train_data():
    training_data = []
    for img in tqdm(os.listdir(TRAIN_DIR)):
        try:
            label = label_img(img)
            path = os.path.join(TRAIN_DIR,img)
            img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
            training_data.append([np.array(img),np.array(label)])
        except:
            pass
    shuffle(training_data)
    np.save('train_data.npy', training_data)
    return training_data

In [5]:
train_data = np.load('train_data.npy',allow_pickle=True)
#train_data = create_train_data()
print((train_data[0][0]))

[[ 76  52 197 ... 240 249 252]
 [ 76  52 199 ... 246 252 255]
 [ 80  55 184 ... 246 253 255]
 ...
 [194 193 161 ...  43  42  45]
 [189 170 179 ...  32  33  35]
 [170 157 170 ...  26  32  25]]


In [7]:
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression
import tensorflow as tf
tf.reset_default_graph()

convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 1], name='input')

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 128, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 64, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = conv_2d(convnet, 32, 5, activation='relu')
convnet = max_pool_2d(convnet, 5)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 2, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=LR, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet, tensorboard_dir='log')



W1129 22:16:15.113828  4740 deprecation_wrapper.py:119] From C:\Users\hp\.conda\envs\DL_ENV\lib\site-packages\tflearn\layers\core.py:81: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1129 22:16:15.113828  4740 deprecation.py:506] From C:\Users\hp\.conda\envs\DL_ENV\lib\site-packages\tflearn\initializations.py:119: calling UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W1129 22:16:15.129450  4740 deprecation.py:323] From C:\Users\hp\.conda\envs\DL_ENV\lib\site-packages\tensorflow\python\util\deprecation.py:507: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent beha

In [13]:

if os.path.exists('{}.meta'.format(MODEL_NAME)):
    model.load(MODEL_NAME)
    print('model loaded!')
key = cv2. waitKey(1)
webcam = cv2.VideoCapture(0)
check, frame = webcam.read()
print(check,"ll") #prints true as long as the webcam is running
print(frame) #prints matrix values of each framecd 
cv2.imshow("Capturing", frame)
cv2.imwrite(filename='saved_img.jpg', img=frame)
webcam.release()
img_new = cv2.imread('saved_img.jpg', cv2.IMREAD_GRAYSCALE)
img_new = cv2.imshow("Captured Image", img_new)
cv2.waitKey(1650)
cv2.destroyAllWindows()
path="E:\\web login\\New folder\\dataset\\cattle122.jpeg"
#path="C:\\Users\\hp\\Documents\\saved_img.jpg"
img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
x=model.predict(img.reshape(-1,50,50,1))
s="not cattle"
if(x[0][0]>x[0][1]):
    s="cattle"
    print("cattle")
else:
    print("not cattle")

model loaded!
True ll
[[[225 227 229]
  [227 227 229]
  [228 228 228]
  ...
  [126 126 144]
  [124 126 144]
  [124 126 144]]

 [[224 226 228]
  [226 226 228]
  [227 227 227]
  ...
  [126 126 144]
  [124 126 144]
  [124 126 144]]

 [[222 224 224]
  [223 223 223]
  [222 222 222]
  ...
  [127 125 142]
  [126 127 143]
  [127 128 144]]

 ...

 [[149 157 166]
  [150 157 168]
  [151 158 171]
  ...
  [ 39  44 110]
  [ 38  45 110]
  [ 37  44 109]]

 [[150 157 170]
  [150 156 172]
  [152 158 175]
  ...
  [ 42  48 111]
  [ 40  46 108]
  [ 36  42 104]]

 [[150 157 170]
  [150 156 172]
  [152 158 175]
  ...
  [ 44  50 113]
  [ 40  46 108]
  [ 34  40 102]]]
cattle


In [14]:
import requests
import json

URL = 'https://www.way2sms.com/api/v1/sendCampaign'

# get request
def sendPostRequest(reqUrl, apiKey, secretKey, useType, phoneNo, senderId, textMessage):
  req_params = {
  'apikey':"LD86DCYCTZTZJD18M074LIVISOSH9TPZ",
  'secret':"MUDJ7EAM6696ISV4",
  'usetype':'stage',
  'phone': "8299159085",
  'message':"Cattle spotted in farm",
  'senderid':"Dharmesh"
  }
  return requests.post(reqUrl, req_params)
if s=="cattle":
    response = sendPostRequest(URL, 'provided-api-key', 'provided-secret',
                           'prod/stage', 'valid-to-mobile',
                           'active-sender-id', 'message-text' )

# print response if you want
print (response.text)

{"code":"200 OK","total-messages-sent":1,"req-type":"post","remaining-sms":22,"message":"Campaign sent successfully.","usetype":"stage","balacne":"0","status":"success"}


In [42]:
train = train_data[:-500]
test = train_data[-500:]

In [43]:
X = np.array([i[0] for i in train]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
Y = [i[1] for i in train]

test_x = np.array([i[0] for i in test]).reshape(-1,IMG_SIZE,IMG_SIZE,1)
test_y = [i[1] for i in test]

In [44]:
model.fit({'input': X}, {'targets': Y}, n_epoch=15, validation_set=({'input': test_x}, {'targets': test_y}), 
    snapshot_step=500, show_metric=True, run_id=MODEL_NAME)

Training Step: 3809  | total loss: 0.01132 | time: 33.537s
| Adam | epoch: 015 | loss: 0.01132 - acc: 0.9965 -- iter: 8064/8099
Training Step: 3810  | total loss: 0.01326 | time: 34.839s
| Adam | epoch: 015 | loss: 0.01326 - acc: 0.9953 | val_loss: 0.39265 - val_acc: 0.9260 -- iter: 8099/8099
--


In [25]:
model.save(MODEL_NAME)